apiVersion: v1
kind: Namespace
metadata:
  name: jellyfin

---

apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---

apiVersion: v1
kind: Namespace
metadata:
  name: homepage

---

apiVersion: v1
kind: Namespace
metadata:
  name: kyverno

---

apiVersion: v1
kind: Namespace
metadata:
  name: nfs-provisioner

---

apiVersion: v1
kind: Namespace
metadata:
  name: cloudflared

---

apiVersion: v1
kind: Namespace
metadata:
  name: silverbullet

---

apiVersion: v1
kind: Namespace
metadata:
  name: karakeep


