apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:InXjw3EsSHtRI98i50Pa,iv:Iqqf23PmH2YaM3NGr5F1SfDJaHAcjLkQtUJKUCa/PHc=,tag:L03ExH6JcK8aDIHxO48jsg==,type:str]
sops:
    age:
        - recipient: age1t35sxk7cxkxk0rgfdmnkcnvky7zuf7g9407d3s03qyggu3w62adqnst5ya
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcnZTczBLdXdpb2JobHRD
            VHdlV3FhczNsLzNHUWhRdm5adFpmWEZTNjBVClMrQk9KMm9VWFFwMm5QUm5kaFFw
            OER6VTZXVUowUHVFMjlGS2FlK3JWdzAKLS0tIGlwYk95allXYjNKUXkvRGJmMWYw
            N00xT0UzR2ZkM1dNYWhmM05LTXN2Y3MK4lJPbVVFK7W7Wd7axWyGWyiQTyhKbGxr
            YTKoFyw+TjcVmzHfLamW1STect7a75tMth+IsaicXP60Ue8KH5zbiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T13:03:10Z"
    mac: ENC[AES256_GCM,data:hn0J/ThAIjjVZqe0WVAeRcQOuobMPYVR6TD3SaWX4W1dvirrmcNbaGmwt0mtkobywep8ODGKXVgsPJXwv5hHEM8o/kCGZy8dcaHF6pgvpMXBO2JTyIg64bCVyt4qtFP18skYNB9JbbvZi0mL4dYgiKaL8BSNWvlIEtsajdi5+WY=,iv:nj3M+Vabhk40EfDvqfu7aCSsvE60SHoe6jyMuz20+Bw=,tag:LIcZCXI7xDwIarjz+RAy+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
