apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: silverbullet-space
  namespace: silverbullet
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-config
  resources:
    requests:
      storage: 5Gi