apiVersion: v1
kind: Secret
metadata:
    name: silverbullet-auth
    namespace: silverbullet
type: Opaque
stringData:
    SB_USER: ENC[AES256_GCM,data:/JgtCN5l7ECZPQFFSFZdRYnE+rNk4w==,iv:jvFxwTKLjmK9txtePRr+h+AiIWrRwFfFZOcaIvMS2rI=,tag:tOoL7vFG95O5WUV2GUjQ8g==,type:str]
sops:
    age:
        - recipient: age1t35sxk7cxkxk0rgfdmnkcnvky7zuf7g9407d3s03qyggu3w62adqnst5ya
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbzNsSEViOEN2OUpuZmtQ
            YVY5c2NVV05oV01waWFZc1lhcUdmZFVxdUNBClFUYXRxM0ZFSzVackptVnNQQ0k5
            cHFxSEdjYzFOeGtYNG11TjZ3VUVBeXMKLS0tIDFtWDZTUlpwbTVZUGNyeHREYko1
            UEJxVEtNcmlqbnpUUUtoeDlKa2xNZGcKp89K/ykLj/TIiO2FwAHCyr9cYDoDuhrZ
            gDywE2siv/kagJwbw5xVINRmqjxa7bPACbOdztcWZkDeOTlNuG5hhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T11:46:59Z"
    mac: ENC[AES256_GCM,data:ZiVXsKi0ZgN0mGOB8Mra8lnFpTqYafubcQuS0vsI6rR11iwETx5HNCW7+adk9ZBUKgCTJPNF3/3VxQ/CTsQfb/wPKrgJexsir63In19CDYKzC8fsjjTeINMLXi2e8ZY628k+uhptWrlC1O9Bta8h/gJQI87mBjFAeiHSIImIzg0=,iv:ZuLxjkkFofqscdXaJqRYT+WV3bRsD4vSg8Movk+jNVo=,tag:KXvB6kZhbE8CchlR5jPasA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
