apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:6S2U5Rq4kmTrDnZgJxjtI0BPNixSYC7M5K74XY9kw/85MdaJZETy1+D4EKbcwErzGh7GZMvzXIuqjLM4/gd6YZobnxuVvY2wWTACA7fosi2gid5ozSlWsrwHBffXdr2ryf5C8+MDxSe0SpZRZatZ1J86sZ15Z6SmuJtaOx77iyO5suEAxyt7aD6DOE2OXryDOu7E+fAjivpoaXLyM5e/+fWNtzEKlZg+6w2swRnNlhQDM5Du547WBQ==,iv:BwatETMqBfPGuD1kl3CqlAw8KRoQ/01/per0fYugaog=,tag:GJ2ZkdzHCGK2DIYYNtt9qg==,type:str]
sops:
    age:
        - recipient: age1t35sxk7cxkxk0rgfdmnkcnvky7zuf7g9407d3s03qyggu3w62adqnst5ya
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWFo4ZEJTUHhwcGY0Q3Ew
            ZWdtdHhSTWo5cWFWdStIcWY3VGRZWXNVV0NFCkhidjFpRm1CRDVidEhjaWJ0UGE0
            djJ4UHpJS2NTTlVTZy9YaXhVb2UzSDgKLS0tIHJhcWI0S1pJNUplcUQwZ2s1U1Fo
            eGozQnoyVm1lZE8wRjUzVVExVDJnZ00K7xHvCDdeZE74nxUXNLPY95cKL76ylsCU
            8Wskd879l3ZJngX60yt0QHPDdScxlmC26exf1YFEDb8SVsffEQZPXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T11:29:36Z"
    mac: ENC[AES256_GCM,data:G3YqQjyiNwjQHTmlc+XY7aWhHgeFXPh8NOOx6VVdRkVw3A93F8O+6ZYTHW94K3Std+5naxndlhHXhKFgpzvX0E98jZPqW9rIorrkHiyIXy2BruOiJ+h4la8RoU/QGTwH3Twm9TwUVm+Y1qkGoqszznMkiDs/nOYrB8Qs9YhBxLE=,iv:mouhYbE56luHA7pdVgOCxk3omfKYrr1ID0mp46SGIKA=,tag:qblTxSb518oWbGvhrPZFUQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0