apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: karakeep-data
  namespace: karakeep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-config
  resources:
    requests:
      storage: 5Gi
      
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meilisearch-data
  namespace: karakeep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-config
  resources:
    requests:
      storage: 2Gi