apiVersion: v1
kind: Secret
metadata:
    name: karakeep-secrets
    namespace: karakeep
type: Opaque
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:WAgWIXq8rcXAapKkB3oSb19sFll2ytVmUBkzsxP17Y1XxQnWWnWL7A8P/f63P7OR,iv:vSUU6m7dxKVgXudNKUzAzoTYxKyu16MLI7FP1GnNztI=,tag:o1WVbtzGNec5zZn8W9X5lA==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:a1V4y3YPxoMD2XrU+wsq+qZ8L88Y2XLvuzs/A7fQT9biKiEHmm7KtzZfeZUxHCJN,iv:osiX1PLoftcbi6Vqt61ER54eB1iPFTKz34kfo/twaM8=,tag:SH1E3Z6VU2CHRa2hZ8xBPg==,type:str]
sops:
    age:
        - recipient: age1t35sxk7cxkxk0rgfdmnkcnvky7zuf7g9407d3s03qyggu3w62adqnst5ya
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVzkvTllyRStQWS9uaGtt
            WHQ2NUZZQnVzZnhSY04yemh6Mk5QNHRlOUJNClYwRHpMV0hsYUthdU9pUnJlVms1
            NjkwNnhBVUQ5U1NXZ210dWU1R3RwZzQKLS0tIFZ6WEJZME1TM0VGTXZZcEdNQkF6
            aUFIZjJqQkJzUmk0ZncyOVNycjRrUjQKPtwbo6i1zW0q6v/DmaoVRCLfBJNpn2Id
            I03rNjO5cxjIBv0gx07z4IvFHKjEhlFGPO3R2i+VmWOz+vw7UaeQuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T06:46:49Z"
    mac: ENC[AES256_GCM,data:QiK0KLRbyaeF3uBtHC7+mij2TpxHjrFKd9CFbPzZ1zaJGj3SPgQNvnjtoletrP1QzBFxjhSyjmMeYXCrKg6jDcqLa6CObu7Z/yimZ+D1h5fVDPRdEsrVpRBUYov5flem9kxTpYNM+2KP8t061qdhq3OGcdiEB1/khHNdXdnxh/A=,iv:l9McZ2r6PULUMJsqhf1BZQMXr292y9TgxU9tO8RvBJM=,tag:IhA5lgGPB41aa6U4+2sqkA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
